### PR TITLE
feat(openapi): improvements to circular ref detection, validation errors

### LINKED ISSUE #1046: No indication of where missing token error occurs with `openapi:validate` command
I have been breaking out primary openapi spec file into more maintainable chunks but I've noticed with validating the primary file, if a child file has an error in it, the error is generic and does not point to where the problem occurred leading to a frustrating hunting and pecking procedure:

image

From what I can tell, this project structure is relatively common:
```
readme_project/
  api_reference.yaml
  components/
    schemas/
      Pet.yaml
      Category.yaml
      User.yaml
```
In this example, if the `Pet.yaml` component has a broken reference to the `Category.yaml` file, running the validate command on the primary `api_reference.yaml` file will not give any indication which component contains the error that was thrown.

e.g. 
```
rdme openapi:validate api_reference.yaml
```

### LINKED ISSUE #1187: value?.ref?.split is not a function when using the validate command
Hi,
Since updating the CLI to v10, my OpenAPI specs fail to validate from this URL:
🔗 https://api.dastra.eu/api/v1/dastra.json

This worked fine in v9.0.5, and manually uploading the specs to the dashboard still works.

**Steps to Reproduce**
Installation method: npm i rdme -g
Specs validation : rdme openapi validate https://api.dastra.eu/api/v1/dastra.json
Screenshot of the issue:
Image
It seems to be related to the ref parser lib

**Environment**
Node version : 22.11.0
Npm version : 10.9.0

### PR DESCRIPTION
**Pull request by erunion**
## 🧰 Changes

Over the past couple weeks I've been rewriting our OpenAPI parser, `@readme/openapi-parser`, to support a new error leveling system -- you can read up on details on this in https://github.com/readmeio/oas/pull/943. This PR pulls in the fruits of my labor there and across `oas` and `oas-normalize`.

* [x] Upgrades `oas-normalize` to pull in our new parser engine and error handling. The error leveling work is not being used within `rdme` but for things like specification validation that our parser does `rdme` will now be able to surface more than one of these errors at a time. 🎉
  * Support for Node 18 has also been removed.
* [x] Upgrades `oas` and `@readme/oas-examples` to pull in the removal of Node 18 support.

All told this overhaul is mostly a drop-in replacement with the exception that instead of `SyntaxError` and `MissingPointerError` exceptions being thrown from the parser for some invalid API definition cases it will now always be a `ValidationError.`

### CODE REVIEW

File: __tests__/commands/openapi/__snapshots__/validate.test.ts.snap [hunk 1]
```diff
@@ -172,10 +172,14 @@ ADDITIONAL PROPERTY must NOT have additional properties
   29 |         "summary": "Finds Pets by status",]
 `;
 
-exports[`rdme openapi validate > error handling > should throw an error if an invalid OpenAPI 3.0 definition is supplied 1`] = `[MissingPointerError: Token "Error" does not exist.]`;
+exports[`rdme openapi validate > error handling > should throw an error if an invalid OpenAPI 3.0 definition is supplied 1`] = `
+[ValidationError: API definition schema validation failed.
```
Comment (erunion) [inline __tests__/commands/openapi/__snapshots__/validate.test.ts.snap:176]: Slightly nicer error message here with this header being shown instead of dumping the user out with "Token "Error" does not exist."

File: package.json [hunk 2]
```diff
@@ -47,7 +47,7 @@
     "@oclif/plugin-help": "^6.2.15",
     "@oclif/plugin-not-found": "^3.2.28",
     "@oclif/plugin-warn-if-update-available": "^3.1.19",
-    "@readme/better-ajv-errors": "^2.0.0",
+    "@readme/better-ajv-errors": "^2.3.2",
```
Comment (erunion) [inline package.json:50]: v2.3.2 was already installed but I just bumped it in the package file.

**Comment by kanadgupta** [comment]
sorry i think #1188 might have caused merge conflicts 🫠

**Review by kanadgupta — APPROVED** [review]
just updated the PR title so it's a bit more customer-facing. LGTM!

one quick non-blocking q — should we add a test that illustrates this? 👇🏽 

> The error leveling work is not being used within `rdme` but for things like specification validation that our parser does `rdme` will now be able to surface more than one of these errors at a time. 🎉

**Comment by erunion** [comment]
> one quick non-blocking q — should we add a test that illustrates this? 👇🏽
> 
> > The error leveling work is not being used within `rdme` but for things like specification validation that our parser does `rdme` will now be able to surface more than one of these errors at a time. 🎉

Feel like that's already well tested across `oas-normalize` and the parser
