### ISSUE TITLE
value?.ref?.split is not a function when using the validate command

### ISSUE THREAD

**Issue by antoinebidault** [readmeio/rdme#1187]
Hi,
Since updating the CLI to v10, my OpenAPI specs fail to validate from this URL:
🔗 https://api.dastra.eu/api/v1/dastra.json

This worked fine in v9.0.5, and manually uploading the specs to the dashboard still works.

**Steps to Reproduce**
Installation method: npm i rdme -g
Specs validation : rdme openapi validate https://api.dastra.eu/api/v1/dastra.json
Screenshot of the issue:
![Image](https://github.com/user-attachments/assets/a9e3766c-1996-489c-b22b-9ce4fde002cb)
It seems to be related to the ref parser lib

**Environment**
Node version : 22.11.0
Npm version : 10.9.0

**Comment by m1k3lm** [comment]
Hi,  

We're encountering the same error with our schemas. What's particularly strange is that the issue appears inconsistently—some machines experience it while others do not, despite using the same Node, npm, and rdme versions. We were able to reproduce the same behavior with both your OpenAPI file and ours.  

To further investigate, we tested using the official Docker images, and the validation error persists across versions:  

- With the latest rdme:  
  ```sh
  docker run --rm node:22 sh -c "npx rdme openapi:validate https://api.dastra.eu/api/v1/dastra.json"
  ```
- Even with rdme 9.0.5:  
  ```sh
  docker run --rm node:22 sh -c "npx rdme@9.0.5 openapi:validate https://api.dastra.eu/api/v1/dastra.json"
  ```
- Testing with an updated npm version:  
  ```sh
  docker run --rm node:22 sh -c "npm install -g npm@11.1.0 && npx rdme@9.0.5 openapi:validate https://api.dastra.eu/api/v1/dastra.json"
  ```
- And with the latest npm:  
  ```sh
  docker run --rm node sh -c "npm install -g npm@11.1.0 && npx rdme openapi:validate https://api.dastra.eu/api/v1/dastra.json"
  ```  

Additionally, we noticed this deprecation warning, which might be related:  
> npm WARN deprecated `@readme/json-schema-ref-parser@1.2.1`: This package is no longer maintained. Please use `@apidevtools/json-schema-ref-parser` instead.  

For reference, here's the [[openapi.json](https://github.com/user-attachments/files/19086673/openapi.json)](https://github.com/user-attachments/files/19086673/openapi.json).  

Let us know if you find any further insights!

**Comment by m1k3lm** [comment]
It seems that this will be fixed in the 10.2 version.

```sh
docker run --rm node sh -c "npx rdme@10.2.0-next.5 openapi:validate https://api.dastra.eu/api/v1/dastra.json" 
```

returns
>- Validating the API definition located at https://api.dastra.eu/api/v1/dastra.json...
https://api.dastra.eu/api/v1/dastra.json is a valid OpenAPI API definition!

**Comment by kanadgupta** [comment]
Hi folks! We've been overhauling our OpenAPI / JSON schema parsing and the changes landed in https://github.com/readmeio/rdme/pull/1189. It looks like @m1k3lm confirmed that the issue is fixed in `rdme@10.2.0-next.5` ([npm release](https://www.npmjs.com/package/rdme/v/10.2.0-next.5), [GitHub release](https://github.com/readmeio/rdme/releases/tag/v10.2.0-next.5)). Please upgrade to this version in the meantime. A release on the `latest` channel with this fix should be available soon.

I'll close this out now but please reach out if you see any other issues. Thanks!

**Comment by aitor** [comment]
@kanadgupta, is this going to be backported to 9.x? Your own documentation cites 9.x as being [actively maintained](https://github.com/readmeio/rdme/blob/main/documentation/migration-guide.md#version-compatibility-matrix). However, right now, there is no way to upload the specs via CLI in non-Refactored projects. All this Refactored thing forces us to redesign our working doc publishing pipeline completely, and keeping the project non-refactored is impossible if we can't automatically upload the OpenAPI specs.

**Comment by aleciten** [comment]
Hey, guys.

We are unable to deploy OpenAPI doc updates whatsoever. 

Getting the `value?.ref?.split is not a function` error in 9.x. 

And the invitation to migrate to "Readme refactored" in order to use `rdme@10.2.0-next.5` results in a blank page:
https://docs.readme.com/main/docs/welcome-to-readme-refactored

**Comment by kanadgupta** [comment]
Hey @aitor @aleciten appreciate the nudge — `v9.2.0` is out now with these changes:

- [npm package (@release-v9 dist-tag)](https://www.npmjs.com/package/rdme/v/9.2.0)
- [GitHub release](https://github.com/readmeio/rdme/releases/tag/v9.2.0)

**Comment by aitor** [comment]
Thank you @kanadgupta. I can confirm that the new release seems to fix the problem:

```
>  npx rdme@9.2.0 openapi:validate https://docs.devengo.com/openapi/626fec4bfc5f40020255f403                                                                              https://docs.devengo.com/openapi/626fec4bfc5f40020255f403 is a valid OpenAPI API definition!
```

**Comment by aleciten** [comment]
Also confirming we can publish with v9. Thanks @kanadgupta !

**Comment by antoinebidault** [comment]
Yes it works ! thanks a lot @kanadgupta  !
